### ISSUE TITLE
npm audit low-severity warning

### ISSUE THREAD

**Issue by trszdev** [primer/stylelint-config-primer#22]
![image](https://user-images.githubusercontent.com/9008471/53304453-21cfe280-3897-11e9-9846-a8bbe8fa85f9.png)

I think it's actually not a vulnerability but I don't like this warning. Solution is about to upgrade `stylelint`  to proper version. Seems like this PR refers to this problem: https://github.com/stylelint/stylelint/pull/3660

**Comment by emplums** [comment]
Thanks for the heads up @trszdev!

**Comment by emplums** [comment]
Looks like primer/css is using an upgraded version of stylelint, which should win out in dependency hoisting! Closing for now.
