### ISSUE TITLE
Unable to get variables.json from @primer/css. Replacements will need to be specified manually

### ISSUE THREAD

**Issue by davincif** [primer/stylelint-config-primer#57]
for the command `npx stylelint "src/**/*.css"`, over the:

package.json file
```json
{
  "name": "demo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "eslint": "npx eslint src/**/*.{js,jsx}",
    "eslint:fix": "npx eslint src/**/*.{js,jsx} --fix"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.1.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.20.0",
    "eslint-plugin-react-hooks": "^4.0.4",
    "stylelint": "^13.5.0",
    "stylelint-config-primer": "^9.0.0",
    "stylelint-config-standard": "^20.0.0"
  }
}
```

and the .stylelintrc.yml file
```yml
files:
  include:
  - 'src/index.css'
  - 'src/**/*.css'
  - 'public/**/*.css'
  ignore:
  - './src/assets/**'
  - './node_modules/**'
  - './docs/**'
  - './trash/**'

extends:
  - stylelint-config-primer
```
 
I get this on my console
> Unable to get variables.json from @primer/css. Replacements will need to be specified manually.
> Unable to get variables.json from @primer/css. Replacements will need to be specified manually.
> Unable to get variables.json from @primer/css. Replacements will need to be specified manually.
> Unable to get variables.json from @primer/css. Replacements will need to be specified manually.
> Unable to get variables.json from @primer/css. Replacements will need to be specified manually.
> Error: Cannot find module '@primer/css/dist/meta.json'
> Require stack:
> - /home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint-config-primer/plugins/lib/primer.js
> - /home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint-config-primer/plugins/no-override.js
> - /home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint/lib/augmentConfig.js
> - /home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint/lib/createStylelint.js
> - /home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint/lib/printConfig.js
> - /home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint/lib/cli.js
> - /home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint/bin/stylelint.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
>     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>     at Module.require (internal/modules/cjs/loader.js:848:19)
>     at require (/home/davincif/Documentos/projects/lab/react/demo/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
>     at requirePrimerFile (/home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint-config-primer/plugins/lib/primer.js:23:10)
>     at /home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint-config-primer/plugins/no-override.js:25:22
>     at /home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint/lib/lintSource.js:209:6
>     at Array.map (<anonymous>)
>     at /home/davincif/Documentos/projects/lab/react/demo/node_modules/stylelint/lib/lintSource.js:208:18
>     at Array.forEach (<anonymous>)

Am I doing something crazy or this is a bug?

**Comment by BinaryMuse** [comment]
@davincif Does the issue resolve if you install `@primer/css` as a dependency or devDependency?

**Comment by heisfullstacked** [comment]
I was facing the same issue and after installing `@primer/css` as devDependency (stylelint-config-primer is installed as devDependency as well) its fixed.

**Comment by davincif** [comment]
Guys, sorry I'll not be able to reproduce the error to try solve the issue, I already gave up using it months ago.
Thank you all for trying to help.
